# Generated by Django 4.2.7 on 2024-01-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
